# Generated by Django 5.2.1 on 2025-05-28 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('medical_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_member_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('medical_history_multiple_session_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('reason_for_change', models.TextField(blank=True, null=True)),
                ('odoo_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('default_code_odoo', models.CharField(blank=True, max_length=255, null=True)),
                ('odoo_order_line_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_path', models.CharField(blank=True, max_length=255, null=True)),
                ('grandfather_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('traveling_to', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('woreda', models.CharField(blank=True, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('allergies', models.TextField(blank=True, null=True)),
                ('chronic_illness', models.TextField(blank=True, null=True)),
                ('medication', models.TextField(blank=True, null=True)),
                ('patient_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('is_credit_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('radiation', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('associated_symptoms', models.TextField(blank=True, null=True)),
                ('aggravating_factors', models.TextField(blank=True, null=True)),
                ('relieving_factors', models.TextField(blank=True, null=True)),
                ('previous_treatments', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('medical_History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpis', to='patients_app.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(max_length=50)),
                ('diagnosis_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('Chronic', 'Chronic')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medical_History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients_app.medicalhistory')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients_app.patient'),
        ),
        migrations.CreateModel(
            name='PatientIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=50)),
                ('smoking_status', models.CharField(choices=[('Never', 'Never'), ('Former', 'Former'), ('Current', 'Current')], max_length=50)),
                ('alcohol_use', models.CharField(choices=[('Never', 'Never'), ('Occasional', 'Occasional'), ('Frequent', 'Frequent')], max_length=50)),
                ('drug_use', models.CharField(choices=[('Never', 'Never'), ('Occasional', 'Occasional'), ('Frequent', 'Frequent')], max_length=50)),
                ('occupation', models.CharField(max_length=255)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('social_history', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('immunization_history', models.TextField(blank=True, null=True)),
                ('previous_medical_procedures', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('medical_History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_intakes', to='patients_app.medicalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('medical_History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients_app.medicalhistory')),
            ],
        ),
    ]
